### PR TITLE
Merge pull request #18 from jdrich/master

### PR DESCRIPTION
**Pull request by leedavis81**
Removing the hard coupling between Drest and the AnnotationDriver.

### CODE REVIEW

**Comment by leedavis81** [comment]
@jdrich I can see you're using the register() function to pass in the config object straight into the Drivers. This was really just intended to pre-load classes that the annotation driver depends on, and I'm not sure the drivers should in anyway touch the config class.

I can see that you simply want to just pass in the path to your config file, which is what $drestConfig->addPathsToConfigFiles() is intended for. Problem is, when using that currently it defaults to using the old drivers, which you need to set explicitly:

$drestConfig->setMetadataDriverClass('\Drest\Mapping\Driver\PhpDriver');

Everything then works fine other than the fact that we need to register all the routes to the internal router, to do this we need all the ORM class names. There was an assumption made that we'd only ever be using annotation driver, and so just collecting that class names from the registered classes was quite easy to do. Now we have other drivers we can't do this. 

Some changes that I've made:

I've left the register() method in place for the purpose of the annotation reader, but this shouldn't really be used in any other instance.

PHP Driver now reads from $paths that are passed in rather than directly from the config that was injected statically. Also, the loadMetadataForClass() shouldn't really throw an exception if it's not found, just return null of no metadata is available for the class.

Also metadata shouldn't be established at driver construct time (for performance reasons). Config path reading is done (and cached) at the point of getAllClassNames().

I think it's ok to hardcode an Symfony\Component\Yaml\Parser instance into the YamlDriver. The implementation kind of relies on this being the parser in place, so injection isn't really necessary.

Fixed tests to reflect these changes

The setup will have changed slightly from how you had it. Now you have to explicitly set the driver you want to use like so:

$drestConfig->setMetadataDriverClass('\Drest\Mapping\Driver\PhpDriver');

// and then add the path to your configs like so:
$drestConfig->addPathsToConfigFiles([
    __DIR__ .'/../config/php/user.php',
    __DIR__ .'/../config/php/profile.php',
]);

**Comment by leedavis81** [comment]
I've moved everything here into https://github.com/leedavis81/drest/pull/21

**Comment by jdrich** [comment]
Does your new implementation support using Doctrine annotations with non-annotation Drest config? I didn't use the existing paths because I didn't want to interfere with that - looks good otherwise. We'll pull and update our implementation.

**Comment by leedavis81** [comment]
It doesn't no. You have to specify the driver up front. So how would that work? Use annotations as default and then overwrite with other? How would you determine which to keep?

**Comment by jdrich** [comment]
You should still be able to use Doctrine annotations with a non-annotation
Drest implementation, IMHO. That's how our implementation was written, at
least. I think your changes prevent that.

So you couldn't add Drest to an existing project that used annotations
without using annotations for the Drest implementation as well. Would be
hairy.

**Comment by leedavis81** [comment]
Ahh I see. I thought you meant a combination of two drest drivers. Yeah the drest driver should have no effect on the driver you use for doctrine. Any data that's needed in drest from doctrine is taken from he metadata factory class. The driver they use is at a lower level. Give it a try and let me know if you have any issues.

**Pull request closed without merging**
